### ISSUE TITLE
爱琴海浪漫银行 火星新费城

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#100]
2020-01-13T13:26:07Z

### 作为星际企业数据提交者，我们如何称呼您？

coulcoul

### 我们如何联系到您？

1314@ai.com

### 星际企业名称是什么

爱琴海浪漫银行

### 星际企业成立时间

1990-12-31

### 企业位置是在哪里

火星新费城

### 星际企业类型

综合爱情

### 星际企业网址

https://love.com

### 公司详情

only love

**Comment by emptymalei** [comment]
closing due to insufficient info:

2020-01-13T13:26:07Z

### 企业位置是在哪里

火星新费城

> The above city doesn't exist

### 星际企业类型

综合爱情


### 星际企业网址

https://love.com
> The provided URL doesn't reflect the indicated company

### 公司详情

only love
> Need more data for this.
