### ISSUE TITLE
人民之友报业集团-TheFriendOfPeople 火星崔哥城

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#113]
https://github.com/InterImm/hub/pull/128
2020-03-02T07:52:47Z

### 作为星际企业数据提交者，我们如何称呼您？

DizzyCui

### 我们如何联系到您？

DizzyCui@163.com

### 星际企业名称是什么

人民之友报业集团-TheFriendOfPeople

### 星际企业成立时间

2017-12-25

### 企业位置是在哪里

火星崔哥城

### 星际企业类型

编辑出版

### 星际企业网址

https://CNR-FOP.com

### 公司详情

人民之友是菅口市第十七中学2019届学生崔东旭以及王一依等人创办的批判班级内的不正之风的杂志，我们也接收来自全国各地的其他学校的投稿。欢迎平台内投稿！也欢迎邮箱投稿：请发送至TheFriendOfPeople@163.com支持*.doc*.docx格式；如有图片或视频请以附件形式发送，文件标题格式为：署名（可匿名）-文章标题-学校（可省略）访问链接以获取模板https://pan.wps.cn/l/sfOwMpZDU

**Comment by tangbababa** [comment]
奥利给干了
