### ISSUE TITLE
新河星 - Glamour Foostar 火星大学城

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#143]
2020-03-10T13:05:02Z

### 作为星际企业数据提交者，我们如何称呼您？

林致

### 我们如何联系到您？

chunglikie0607@gmail.com

### 星际企业名称是什么

新河星 - Glamour Foostar

### 星际企业成立时间

2020-03-10

### 企业位置是在哪里

火星大学城

### 星际企业类型

食品生产

### 星际企业网址

http://glamourfoodstar.com

### 公司详情

属于太空食品生产公司，已在2022年创下股市投资回报率的新记录。目前在食品零售市场占据第二高的份额，同时与星际安全食品局合作研究缩放性食品科技。

**Comment by emptymalei** [comment]
#144
