### ISSUE TITLE
黄昏星-The evening star 火星南河城

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#145]
2020-03-10T13:53:59Z

### 作为星际企业数据提交者，我们如何称呼您？

Hesper Young

### 我们如何联系到您？

2214229882@qq.com

### 星际企业名称是什么

黄昏星-The evening star

### 星际企业成立时间

2104-06-24

### 企业位置是在哪里

火星南河城

### 星际企业类型

太空犯罪

### 公司详情

时属杨家的私人家族企业，其创始人为距今100年前的海斯帕小姐。该企曾成功打击多个太空走私集团头目并向世人揭露出太空走私者联盟内部交易的黑幕，同时致力于太空大盗的追捕行动。与打击太空犯罪局为长期友好合作关系。

**Comment by emptymalei** [comment]
#146
