### ISSUE TITLE
杭黄 楼兰城

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#147]
2020-03-13T05:27:37Z

### 作为星际企业数据提交者，我们如何称呼您？

Nck

### 我们如何联系到您？

nhuang817@iCloud.com

### 星际企业名称是什么

杭黄

### 星际企业成立时间

2220-02-22

### 企业位置是在哪里

楼兰城

### 星际企业类型

环境保护

### 公司详情

地球人创建的环境保护公司，致力于进行火星生活，建筑垃圾回收再利用

**Comment by emptymalei** [comment]
#148
