### ISSUE TITLE
魚湯火星考古研究所 亚特兰蒂斯城

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#149]
2020-03-18T23:59:11Z

### 作为星际企业数据提交者，我们如何称呼您？

杰米扬魚湯

### 我们如何联系到您？

smk11205002@outlook.com

### 星际企业名称是什么

魚湯火星考古研究所

### 星际企业成立时间

2060-02-11

### 企业位置是在哪里

亚特兰蒂斯城

### 星际企业类型

火星考古

### 公司详情

火星考古研究所

**Comment by emptymalei** [comment]
#150 

http://interimm.org/hub/companies.html#company-azbvk54fdv9y0n8iz9azbvk5rnrqub66-full
