### ISSUE TITLE
天启科技 川陀城

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#151]
2020-03-20T07:35:53Z

### 作为星际企业数据提交者，我们如何称呼您？

Reymond

### 我们如何联系到您？

ty199644@sina.com

### 星际企业名称是什么

天启科技

### 星际企业成立时间

2030-03-02

### 企业位置是在哪里

川陀城

### 星际企业类型

生物医疗

### 公司详情

专注于人类未来的高新科技技术企业

**Comment by emptymalei** [comment]
缺少细节
