### ISSUE TITLE
深空资源开发公司 火星端点城南侧

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#155]
2020-03-22T20:09:09Z

### 作为星际企业数据提交者，我们如何称呼您？

Aipoter

### 我们如何联系到您？

1182026036@qq.com

### 星际企业名称是什么

深空资源开发公司

### 星际企业成立时间

2037-07-17

### 企业位置是在哪里

火星端点城南侧

### 星际企业类型

资源开发

### 公司详情

航星旗下子公司，主管太阳系行星的资源开发与利用，是航星公司重要的资金来源。

**Comment by emptymalei** [comment]
#156
