### ISSUE TITLE
璐-Blu 火星楼兰城

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#157]
2020-03-23T01:08:44Z

### 作为星际企业数据提交者，我们如何称呼您？

MagicKyaw

### 我们如何联系到您？

1355455605@qq.com

### 星际企业名称是什么

璐-Blu

### 星际企业成立时间

2020-03-23

### 企业位置是在哪里

火星楼兰城

### 星际企业类型

星际科研

### 星际企业网址

https://kyaw.com

### 公司详情

本公司为Kyaw基金子公司，公司的使命是让宇宙观测达到极限可视化。

我们的业务包括星际未知探索、宇宙物质分析、宇宙进程推演、宇宙定位、未知物质检测以及其他业务。除此之外， 我们同时为我们平台上的消费者、商家以及有合作意向的科研单位提供技术支持、载具搭乘、实验室提供、产品鉴定和相关融资服务。围绕着我们的平台与业务，一个涵盖了消费者、商家、品牌、实体门店、第三方服务提供商、战略合作伙伴及其他企业的数字经济体已经建立起来。

**Comment by emptymalei** [comment]
#162
