### ISSUE TITLE
Magic基金 火星南河城

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#159]
2020-03-23T01:35:35Z

### 作为星际企业数据提交者，我们如何称呼您？

MagicKyaw

### 我们如何联系到您？

1355455605@qq.com

### 星际企业名称是什么

Magic基金

### 星际企业成立时间

2020-03-23

### 企业位置是在哪里

火星南河城

### 星际企业类型

投资金融

### 星际企业网址

http://quantumfundsonline.com/

### 公司详情

Magic基金是星系著名的大规模对冲基金，中国金融家Kyaw·刘旗下经营的四个对冲基金之一。Magic基金是高风险基金，主要借款在星系范围内投资于股票、债券、外汇和基础设施建设开发。Magic基金没有在地球登记注册，而是在火星离岸注册。它主要采取私募方式筹集资金。

**Comment by emptymalei** [comment]
#160
