### ISSUE TITLE
独角定制 亚特兰蒂斯

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#163]
2020-03-24T03:01:39Z

### 作为星际企业数据提交者，我们如何称呼您？

unicorn

### 我们如何联系到您？

3256025550@qq.com

### 星际企业名称是什么

独角定制

### 星际企业成立时间

2020-03-14

### 企业位置是在哪里

亚特兰蒂斯

### 星际企业类型

私人物品定制

### 公司详情

独角高定在高品位人生中掀起一波热潮 成为了高端人士发展个性的不二选择

**Comment by emptymalei** [comment]
#164
