### ISSUE TITLE
生命图画-TPL 火星川陀城

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#165]
2020-03-25T07:38:01Z

### 作为星际企业数据提交者，我们如何称呼您？

狼偏

### 我们如何联系到您？

1752116931@qq.com

### 星际企业名称是什么

生命图画-TPL

### 星际企业成立时间

2020-08-13

### 企业位置是在哪里

火星川陀城

### 星际企业类型

医疗技术

### 公司详情

生命图画，从事有关医疗、药物研究等方面的国际组织，集结了全宇宙内将近5万名来自两大国家的、各个医学及药学领域的专家，致力于医疗事业的发展。

**Comment by emptymalei** [comment]
#166
