### ISSUE TITLE
祝融 火星参宿城

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#167]
2020-03-26T05:47:37Z

### 作为星际企业数据提交者，我们如何称呼您？

景书

### 我们如何联系到您？

1544875366@qq.com

### 星际企业名称是什么

祝融

### 星际企业成立时间

2027-03-26

### 企业位置是在哪里

火星参宿城

### 星际企业类型

火星建筑业，太空探索旅游

### 公司详情

基于火星的创业集团，致力于火星城市建设与建筑改造，在21世纪后半叶成为火星建筑业龙头。同时发展星际旅行产业。

**Comment by emptymalei** [comment]
#170
