### ISSUE TITLE
空间银河 中国山都重庆

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#171]
2020-03-27T05:27:12Z

### 作为星际企业数据提交者，我们如何称呼您？

帝江

### 我们如何联系到您？

1615840866@qq.com

### 星际企业名称是什么

空间银河

### 星际企业成立时间

2000-10-01

### 企业位置是在哪里

中国山都重庆

### 星际企业类型

空间跳跃

### 星际企业网址

http://kongjianyinhe.com

### 公司详情

该公司属于水瓶银河集团子公司。其开发的太空船系列在20世纪20年代占据百分之50市场份额。主要的飞船系列分S，L以及SL三个类别

**Comment by emptymalei** [comment]
#172
