### ISSUE TITLE
Spirit Energy Research Institute-Stand Power Bolide City

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#173]
2020-03-28T01:15:58Z

### 作为星际企业数据提交者，我们如何称呼您？

Mr.Human

### 我们如何联系到您？

1065568727@qq.com

### 星际企业名称是什么

Spirit Energy Research Institute-Stand Power

### 星际企业成立时间

1987-01-02

### 企业位置是在哪里

Bolide City

### 星际企业类型

精神力.超心理学研究基金会

### 公司详情

本公司始创于1987年，2010年，精神力学研究的突破，使人类不再被定义为碳基生命，2011年，黑客组织将子公司（BV）入侵成功，大量数据被盗取，2011年5月，黑客组织被全面曝光，所有组织成员被处以枪决。经过焚烧，场地没有留下任何一具遗体，但在2012年，民间精神力雇佣兵出现，从全球多个绮（城市单位）同时发动进攻，史称“灰色流苏事件”。六个月后，2亿地球作战单位（包括机械生命）失去战斗能力，暴乱被压制，头目当场死亡（肉体和精神的死亡），迫于媒体与民众的压力下，地球政府强制将本公司转移至火星继续进行研究。

**Comment by emptymalei** [comment]
Invalid
