### ISSUE TITLE
宇涵医院 天狼域

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#174]
2020-03-28T01:34:00Z

### 作为星际企业数据提交者，我们如何称呼您？

Octopus

### 我们如何联系到您？

1311931211@qq.com

### 星际企业名称是什么

宇涵医院

### 星际企业成立时间

2032-12-11

### 企业位置是在哪里

天狼域

### 星际企业类型

医疗

### 公司详情

个人私企，为历年移民至火星的所有人提供一定程度的医疗体系服务，包括来到火星后的适应问题，及一些宇宙射线导致的疾病和理疗康复.

**Comment by emptymalei** [comment]
#175
