### ISSUE TITLE
薛式重工 马里亚纳大海沟

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#177]
2020-04-02T00:47:50Z

### 作为星际企业数据提交者，我们如何称呼您？

薛总

### 我们如何联系到您？

3321615794@qq.com

### 星际企业名称是什么

薛式重工

### 星际企业成立时间

1436-04-12

### 企业位置是在哪里

马里亚纳大海沟

### 星际企业类型

重工

### 公司详情

智造大形态宇宙航轮

**Comment by emptymalei** [comment]
Inconsistent
