### ISSUE TITLE
丘比羡鱼 星坠城

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#179]
2020-04-03T11:12:45Z

### 作为星际企业数据提交者，我们如何称呼您？

丘比

### 我们如何联系到您？

2463026412@qq.com

### 星际企业名称是什么

丘比羡鱼

### 星际企业成立时间

2020-04-11

### 企业位置是在哪里

星坠城

### 星际企业类型

通讯

### 公司详情

丘比羡鱼集团公司，其开发的小行星间通讯设备，在20世纪20年代的小行星之间占据了大部分市场份额。

**Comment by emptymalei** [comment]
#180
