### ISSUE TITLE
国际深空发展组织-IDSDO 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#192]
2020-04-06T16:38:14Z

### 作为星际企业数据提交者，我们如何称呼您？

Agent14th

### ，您的星际企业名称是什么

国际深空发展组织-IDSDO

### 请您选择成立时间

2025-01-12

### 的总部是在哪里

地球

### 的企业类型

太空探索旅游

### 公司详情

由中国，美国欧盟，俄罗斯等航天大国签署共同成立，在开发火星之前已有凌霄1、凌霄2两个太空城市和伊顿月球南极基地，为了进行火星的开发于2065年建造了VULCAN火星轨道城市

### ，我们如何联系到您？

2391948210@qq.com

**Comment by emptymalei** [comment]
#193 
http://interimm.org/hub/companies/company-qjsoosgdgtv0elffmsqjsooemajylhle/
