### ISSUE TITLE
远航太空旅游探索有限公司 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#210]
2020-04-30T05:22:51Z

### 作为星际企业数据提交者，我们如何称呼您？

张舟元

### ，您的星际企业名称是什么

远航太空旅游探索有限公司

### 请您选择成立时间

2036-10-24

### 的总部是在哪里

火星参宿城(Sirius City)：2123 年成立；伊希地城市圈

### 的企业类型

太空探索旅游

### 的网址

https://www.est.com.cn

### 公司详情

时属远航太空集团，其开发的远航系列航空飞机及太空飞船在21世纪30年代末的亚轨道热潮中占据大部分市场份额，并开发了一种新行业——太空建筑业。后并入轨道旅游局，成为太空旅游探索行业巨头。

### ，我们如何联系到您？

3534583961@qq.com

**Comment by emptymalei** [comment]
https://github.com/InterImm/hub/pull/212
