### ISSUE TITLE
云息痛制药 Yunxitong Pharmaceutical 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#213]
2020-05-01T03:19:26Z

### 作为星际企业数据提交者，我们如何称呼您？

yxt

### ，您的星际企业名称是什么

云息痛制药 Yunxitong Pharmaceutical

### 请您选择成立时间

2035-03-11

### 的总部是在哪里

地球

### 的企业类型

医疗技术

### 的网址

https://www.interimmag.com.cn

### 公司详情

时属于云北黑药公司，其为适应星际移民热潮，在21世纪30年代开创治疗星际跳跃所带来不适的药物，目前是晕星药领域的领头羊

### ，我们如何联系到您？

tanlang-yu@qq.com

**Comment by emptymalei** [comment]
https://github.com/InterImm/hub/pull/214
