### ISSUE TITLE
Solar Entrainment Co. 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#219]
2020-05-11T13:04:32Z

### 作为星际企业数据提交者，我们如何称呼您？

Nye

### ，您的星际企业名称是什么

Solar Entrainment Co.

### 请您选择成立时间

2023-07-11

### 的总部是在哪里

火星端点城(Terminus City)：2156 年成立；希腊城市圈；农业为主的城市

### 的企业类型

服务业

### 的网址

https://li6834300.github.io

### 公司详情

时属维珍集团子公司，其开发的太空船系列亚轨道飞船在 20 世纪 20 年代的亚轨道旅游热潮中占据了大部分市场份额。后并入轨道旅游局。

### ，我们如何联系到您？

kenli@nyu.edu

**Comment by emptymalei** [comment]
https://github.com/InterImm/hub/pull/220
