### ISSUE TITLE
Alien Sex Service Center 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#223]
2020-06-01T17:45:40Z

### 作为星际企业数据提交者，我们如何称呼您？

K.索菲亚

### ，您的星际企业名称是什么

Alien Sex Service Center

### 请您选择成立时间

2020-06-01

### 的总部是在哪里

火星亚特兰帝斯城(Atlantis City)：2250 年成立；亚马逊城市圈

### 的企业类型

服务业

### 公司详情

时属索菲亚集团子公司，其开发的外星人交配体验在21世纪20年代风靡宇宙。

### ，我们如何联系到您？

sophielee0704@gmail.com

**Comment by emptymalei** [comment]
#224
