### ISSUE TITLE
艾琳虚空财团 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#225]
2020-06-03T11:48:56Z

### 作为星际企业数据提交者，我们如何称呼您？

神崎千華

### ，您的星际企业名称是什么

艾琳虚空财团

### 请您选择成立时间

2020-06-03

### 的总部是在哪里

火星视界城(Horizon City)：2148 年成立；子午线城市圈；城内的视界星港是火星最大的星港

### 的企业类型

投资金融

### 公司详情

任何行为与物品均有投资的价值

### ，我们如何联系到您？

2420166133@qq.com

**Comment by emptymalei** [comment]
#226
