### ISSUE TITLE
古藤星系 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#227]
2020-06-20T02:57:25Z

### 作为星际企业数据提交者，我们如何称呼您？

离家出走的熊

### ，您的星际企业名称是什么

古藤星系

### 请您选择成立时间

2020-06-24

### 的总部是在哪里

火星楼兰城(Kroran City)：2250 年成立；亚马逊城市圈

### 的企业类型

投资金融

### 的网址

https://https:\\www.gutengxingxi.com.cn

### 公司详情

古藤星系公司为大型综合类公司，主要为投资金融类后发展大量子公司，包含影视，食品，房地产等

### ，我们如何联系到您？

1728895819@qq.com

**Comment by emptymalei** [comment]
#228
