### ISSUE TITLE
猫咪帝国驻火星大使馆 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#229]
2020-06-21T04:06:31Z

### 作为星际企业数据提交者，我们如何称呼您？

英短

### ，您的星际企业名称是什么

猫咪帝国驻火星大使馆

### 请您选择成立时间

2123-01-01

### 的总部是在哪里

火星天狼城(Betelgeuse City)：2123 年成立；伊希地城市圈

### 的企业类型

其他

### 的网址

https://myspace.windows93.net/?id=6134

### 公司详情

猫咪帝国大使馆，为CATLAND公民提供服务与保障。

### ，我们如何联系到您？

orangeexx@outlook.com

**Comment by emptymalei** [comment]
#230
