### ISSUE TITLE
project utopia 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#233]
2020-06-24T08:00:07Z

### 作为星际企业数据提交者，我们如何称呼您？

CuSOfour

### ，您的星际企业名称是什么

project utopia

### 请您选择成立时间

2345-06-17

### 的总部是在哪里

火星星坠城(Bolide City)：2165 年成立；子午线城市圈；围绕行星地质大学（Planetary Geology University）建成。

### 的企业类型

科研

### 公司详情

project utopia公司作为一家科研公司，以“不断研发，让全宇宙都幸福”作为理念，研发出不计其数的产品，其中最知名的有：U-0617型小型家用飞行器，R-66177型便携式机器人，同时也参与了q型戴森球的研发，很大程度上推进了科技的发展进步。

### ，我们如何联系到您？

3612316206@qq.com

**Comment by emptymalei** [comment]
#234
