### ISSUE TITLE
Mars Basketball Association 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#235]
2020-07-02T08:32:23Z

### 作为星际企业数据提交者，我们如何称呼您？

Mike Stone

### ，您的星际企业名称是什么

Mars Basketball Association

### 请您选择成立时间

2130-10-02

### 的总部是在哪里

火星南河城(Procyon City)：2123 年成立；伊希地城市圈

### 的企业类型

休闲娱乐

### 公司详情

一群在休息日打篮球的工程师们决定成立一个半职业化的篮球联盟，后来MBA成为了火星人类体育事业的奠基者

### ，我们如何联系到您？

894560203@qq.com

**Comment by emptymalei** [comment]
#236
