### ISSUE TITLE
Homeland 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#237]
2020-07-05T06:47:28Z

### 作为星际企业数据提交者，我们如何称呼您？

Mr.Song

### ，您的星际企业名称是什么

Homeland

### 请您选择成立时间

2021-11-07

### 的总部是在哪里

太空城市瀑布城：2040 年成立；第一个大型太空城市

### 的企业类型

军事

### 的网址

https://www.homeland.com

### 公司详情

故土(Homeland)公司曾是地球最大私人军火供应商，为多达146个国家提供军火支持与维护。于2021年在瀑布城成立全资子公司

### ，我们如何联系到您？

3065268857@qq.com

**Comment by emptymalei** [comment]
#240
