### ISSUE TITLE
黑山 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#238]
2020-07-05T07:02:56Z

### 作为星际企业数据提交者，我们如何称呼您？

Nicholassong

### ，您的星际企业名称是什么

黑山

### 请您选择成立时间

1823-05-15

### 的总部是在哪里

地球

### 的企业类型

投资金融

### 的网址

https://黑山.com

### 公司详情

一家来自地球的投资公司

### ，我们如何联系到您？

3065268857@qq.com

**Comment by emptymalei** [comment]
#239
