### ISSUE TITLE
太空能源-Space energy 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#241]
2020-07-05T10:44:17Z

### 作为星际企业数据提交者，我们如何称呼您？

123

### ，您的星际企业名称是什么

太空能源-Space energy

### 请您选择成立时间

2061-07-05

### 的总部是在哪里

太空城市星夜城：2042 年成立

### 的企业类型

能源矿产

### 的网址

https://Space energy.com

### 公司详情

隶属于黑山财团，为火星上最大的能源供应商。主要研究与发展可控核聚变技术

### ，我们如何联系到您？

3065268857@qq.com

**Comment by emptymalei** [comment]
#244
