### ISSUE TITLE
星晨矿业 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#242]
2020-07-05T10:49:33Z

### 作为星际企业数据提交者，我们如何称呼您？

Atew

### ，您的星际企业名称是什么

星晨矿业

### 请您选择成立时间

2062-07-05

### 的总部是在哪里

欧罗巴

### 的企业类型

能源矿产

### 的网址

https://start.com

### 公司详情

为黑石财团全资控股子公司，总部设置于欧罗巴，主要参与外太空特殊矿物开采与加工。

### ，我们如何联系到您？

3065268857@qq.com

**Comment by emptymalei** [comment]
#243
