### ISSUE TITLE
泰坦重工 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#245]
2020-07-07T07:21:51Z

### 作为星际企业数据提交者，我们如何称呼您？

So

### ，您的星际企业名称是什么

泰坦重工

### 请您选择成立时间

2114-02-07

### 的总部是在哪里

火星参宿城(Sirius City)：2123 年成立；伊希地城市圈

### 的企业类型

飞船制造

### 的网址

https://www.Titan industry.com

### 公司详情

致力于超大型外太空探索飞船的建造，占据市场过半份额

### ，我们如何联系到您？

123@35.com

**Comment by emptymalei** [comment]
#246
