### ISSUE TITLE
FDG-娱乐集团 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#252]
2020-07-10T16:12:59Z

### 作为星际企业数据提交者，我们如何称呼您？

power-carton

### ，您的星际企业名称是什么

FDG-娱乐集团

### 请您选择成立时间

2025-07-05

### 的总部是在哪里

火星南河城(Procyon City)：2123 年成立；伊希地城市圈

### 的企业类型

休闲娱乐

### 公司详情

新兴娱乐团体，旗下包含一个完整的娱乐团队和一个完整的创作者社区，致力于净化互联网，拯救世界

### ，我们如何联系到您？

13572207575@163.com

**Comment by emptymalei** [comment]
#253
