### ISSUE TITLE
暗枫工业-Black Maple Industry 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#255]
2020-08-07T06:23:15Z

### 作为星际企业数据提交者，我们如何称呼您？

Gwnnem

### ，您的星际企业名称是什么

暗枫工业-Black Maple Industry

### 请您选择成立时间

2098-06-12

### 的总部是在哪里

泰坦

### 的企业类型

飞船制造

### 公司详情

暗枫工业 重点开发外太空机械设备，并逐步开始制造外星地面设备，并且占据一部分市场份额

### ，我们如何联系到您？

a929945548@163.com

**Comment by emptymalei** [comment]
#256
