### ISSUE TITLE
鹊语 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#257]
2020-08-09T12:35:23Z

### 作为星际企业数据提交者，我们如何称呼您？

That's enough

### ，您的星际企业名称是什么

鹊语

### 请您选择成立时间

2021-07-01

### 的总部是在哪里

地球

### 的企业类型

通讯

### 公司详情

致力于提供太阳系内免费快捷的民用通讯服务，在地球与各行星间有多个信号中继卫星。与重生倡议（Rebirth Initiative）有科技方面的长期合作

### ，我们如何联系到您？

bedrockchrithy@163.com

**Comment by emptymalei** [comment]
#258
