### ISSUE TITLE
“重生”倡议-Rebirth Initiative 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#259]
2020-08-09T15:02:44Z

### 作为星际企业数据提交者，我们如何称呼您？

Ivy_C

### ，您的星际企业名称是什么

“重生”倡议-Rebirth Initiative

### 请您选择成立时间

1945-10-01

### 的总部是在哪里

地球

### 的企业类型

科研

### 的网址

http://rebirth-initiative-interimm.wikidot.com/

### 公司详情

第二次世界大战结束后，世界各国重新开始审视科学技术对世界的影响。不可否认，先进的科技运用在战争中导致的很多平民伤亡；但是更多的，先进的科技会大限度的阻止大规模战争的爆发。1945年10月1日，美苏领导人秘密会晤，象征着重生倡议的创立。
重生倡议以通过发展科学技术，提高人类生活质量与阻止战争为主旨，在科技方面有较为卓越的成就。
比起“倡议会”，重生倡议更像一个大规模的科研组织。这里集结了在各个方面有卓越成就的人才，是目前体量较大的公立科研组织

### ，我们如何联系到您？

ivyc_here@foxmail.com

**Comment by emptymalei** [comment]
#260
