### ISSUE TITLE
红纹蚂重型机械公司 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#261]
2020-08-12T01:43:50Z

### 作为星际企业数据提交者，我们如何称呼您？

康豪

### ，您的星际企业名称是什么

红纹蚂重型机械公司

### 请您选择成立时间

2054-06-12

### 的总部是在哪里

火星参宿城(Sirius City)：2123 年成立；伊希地城市圈

### 的企业类型

飞船制造

### 公司详情

从地球时代开始设计并制造重型设备，是前往火星开发的第一批工业企业，对火星陆地重型设备几乎形成垄断地位

### ，我们如何联系到您？

a929945548@163.com

**Comment by emptymalei** [comment]
#262
