### ISSUE TITLE
荧惑安保 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#263]
2020-08-16T15:01:04Z

### 作为星际企业数据提交者，我们如何称呼您？

李梓枫

### ，您的星际企业名称是什么

荧惑安保

### 请您选择成立时间

2073-01-27

### 的总部是在哪里

地球

### 的企业类型

安保

### 公司详情

主要负责火星与地球之间运输的安保工作，是唯一一家负责星际运输安保的公司，在2203年成为星际移民局指定安保公司。

### ，我们如何联系到您？

1079332015@qq.com

**Comment by emptymalei** [comment]
#264
