### ISSUE TITLE
远东星际博物馆 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#265]
2020-08-19T10:39:08Z

### 作为星际企业数据提交者，我们如何称呼您？

远东

### ，您的星际企业名称是什么

远东星际博物馆

### 请您选择成立时间

2046-06-04

### 的总部是在哪里

太空城市瀑布城：2040 年成立；第一个大型太空城市

### 的企业类型

教育

### 公司详情

文明以止

### ，我们如何联系到您？

gifcstu@gmail.com

**Comment by emptymalei** [comment]
#266
