### ISSUE TITLE
太空幸福协会 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#267]
2020-08-30T03:39:32Z

### 作为星际企业数据提交者，我们如何称呼您？

好爱睡觉

### ，您的星际企业名称是什么

太空幸福协会

### 请您选择成立时间

2333-08-09

### 的总部是在哪里

火星奇点城(Singularity City)：2145 年成立；子午线城市圈；安逸的生活环境

### 的企业类型

休闲娱乐

### 的网址

https://www.happiness.com

### 公司详情

.居民可将自己的幸福时刻汇聚于此，欢迎光临~

### ，我们如何联系到您？

3507484204@qq.com

**Comment by emptymalei** [comment]
#268
