### ISSUE TITLE
银河矿业有限公司 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#269]
2020-08-30T09:51:00Z

### 作为星际企业数据提交者，我们如何称呼您？

LI

### ，您的星际企业名称是什么

银河矿业有限公司

### 请您选择成立时间

2023-06-09

### 的总部是在哪里

太空城市星夜城：2042 年成立

### 的企业类型

能源矿产

### 公司详情

星际采矿

### ，我们如何联系到您？

1023710732@qq.com

**Comment by emptymalei** [comment]
无细节
