### ISSUE TITLE
万路通星际快递股份有限公司-VanluTon Interstellar Express 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#273]
2020-11-15T12:58:36Z

### 作为星际企业数据提交者，我们如何称呼您？

WJ08

### ，您的星际企业名称是什么

万路通星际快递股份有限公司-VanluTon Interstellar Express

### 请您选择成立时间

2045-04-11

### 的总部是在哪里

火星南河城(Procyon City)：2123 年成立；伊希地城市圈

### 的企业类型

运输

### 公司详情

星际贸易时代下的产物，致力于为不同星际城市之间的居民及企业提供平价的快递运输服务，使普通人能够享受到太空时代的精彩与便捷。

### ，我们如何联系到您？

763844053@qq.com

**Comment by emptymalei** [comment]
http://interimm.org/hub/companies/company-entotrfe91wgcsplbrkqnym95entotrf/
