### ISSUE TITLE
Nolow Galactic 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#277]
2021-01-14T08:29:23Z

### 作为星际企业数据提交者，我们如何称呼您？

fire

### ，您的星际企业名称是什么

Nolow Galactic

### 请您选择成立时间

2021-01-14

### 的总部是在哪里

月球

### 的企业类型

能源矿产

### 公司详情

some energy from the sun turn to something on the moon

### ，我们如何联系到您？

962018024@qq.com

**Comment by emptymalei** [comment]
#278
