### ISSUE TITLE
Cyberpunk Fight Against the God 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#279]
2021-02-04T01:08:06Z

### 作为星际企业数据提交者，我们如何称呼您？

Kai HCH

### ，您的星际企业名称是什么

Cyberpunk Fight Against the God

### 请您选择成立时间

2077-06-30

### 的总部是在哪里

火星视界城(Horizon City)：2148 年成立；子午线城市圈；城内的视界星港是火星最大的星港

### 的企业类型

军事

### 公司详情

在2076年成立，先致力于高新技术研究开发，后发展成为太空安保、武器及设施研发公司，并迅速发展。2144年，非法介入了一场恐怖分子袭击事件，剿灭其全部后，董事会决定与多家太空企业进行合作，进行行星、恒星级武器开发，同时地下部分开始进行枪火走私。

### ，我们如何联系到您？

2423990661@qq.com

**Comment by emptymalei** [comment]
#280
