### ISSUE TITLE
长星宇际-Just Universe 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#281]
2021-04-23T15:24:47Z

### 作为星际企业数据提交者，我们如何称呼您？

林长星-Justyna

### ，您的星际企业名称是什么

长星宇际-Just Universe

### 请您选择成立时间

2021-04-03

### 的总部是在哪里

太空城市星夜城：2042 年成立

### 的企业类型

休闲娱乐

### 公司详情

长星宇际是一家多元公司，主要以培养艺人为主，副业是科研，发现新天体和探秘暗物质暗能量

### ，我们如何联系到您？

3136508968@qq.com

**Comment by emptymalei** [comment]
http://interimm.org/hub/companies/company-9sof90yst7rfg2e418t19sof93tsnwxa/
