### ISSUE TITLE
小土村房地产-Local Village Real Estate 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#283]
2021-05-01T03:23:06Z

### 作为星际企业数据提交者，我们如何称呼您？

李林

### ，您的星际企业名称是什么

小土村房地产-Local Village Real Estate

### 请您选择成立时间

2022-03-01

### 的总部是在哪里

火星南河城(Procyon City)：2123 年成立；伊希地城市圈

### 的企业类型

房地产

### 公司详情

早期移民自发建立的房地产公司，一开始致力于提供舒适、人性化的居住环境，以“人人有房住”为服务宗旨，专注住宅和商业房地产开发。

### ，我们如何联系到您？

2562414413@qq.com

**Comment by emptymalei** [comment]
PR: https://github.com/InterImm/hub/pull/285

Online at: http://interimm.org/hub/companies/company-be1dqueze9f8ilpbe1dquvg3w1qzt9i5/
