### ISSUE TITLE
俊哲宇宙文化传媒公司-火星工作室 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#286]
2021-05-01T21:10:26Z

### 作为星际企业数据提交者，我们如何称呼您？

浪浪钉

### ，您的星际企业名称是什么

俊哲宇宙文化传媒公司-火星工作室

### 请您选择成立时间

2129-05-11

### 的总部是在哪里

火星南河城(Procyon City)：2123 年成立；伊希地城市圈

### 的企业类型

休闲娱乐

### 的网址

https://www.douban.com/group/695375/

### 公司详情

本工作室直属于俊哲宇宙文化传媒公司地球总部，是探索外太空文化娱乐传媒范式的先锋组织，也是进行星际文化交流的排头兵。

### ，我们如何联系到您？

luhan040710@foxmail.com

**Comment by emptymalei** [comment]
PR: #287 
Online: http://interimm.org/hub/companies/company-ypfbogrqi22962fbooypfbe0yhohcabn/
