### ISSUE TITLE
水漂资本 - Ducks & Drakes Capital 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#288]
2021-05-02T02:26:14Z

### 作为星际企业数据提交者，我们如何称呼您？

李林 Lilin

### ，您的星际企业名称是什么

水漂资本 - Ducks & Drakes Capital

### 请您选择成立时间

2023-09-22

### 的总部是在哪里

火星参宿城(Sirius City)：2123 年成立；伊希地城市圈

### 的企业类型

投资金融

### 公司详情

产业投资基金，专注于火星可持续发展。广泛投资于生物科技、能源、新材料、教育、消费娱乐、基础设施建设、人工智能、机器人等领域的火星创业型公司。火星联合储备委员会发起人之一。

### ，我们如何联系到您？

2562414413@qq.com

**Comment by emptymalei** [comment]
#291 
http://interimm.org/hub/companies/company-856c67kjcmttzbea7oc46856c67klj97/
