### ISSUE TITLE
绝望解药 Despaikiller Psycho Consultation 

### ISSUE THREAD

**Issue by InterImmCenter** [InterImm/hub#289]
2021-05-02T02:55:42Z

### 作为星际企业数据提交者，我们如何称呼您？

李林 Lilin

### ，您的星际企业名称是什么

绝望解药 Despaikiller Psycho Consultation

### 请您选择成立时间

2124-04-12

### 的总部是在哪里

火星天狼城(Betelgeuse City)：2123 年成立；伊希地城市圈

### 的企业类型

医疗技术

### 公司详情

服务于火星移民者的连锁制心理咨询机构，引入AI技术，解决移民者和AI机器人常见或极端的心理问题。附属机构包括绝望解药人工智能研究中心、伊希地精神卫生中心和伊希地精神科学研究所。

### ，我们如何联系到您？

2562414413@qq.com

**Comment by emptymalei** [comment]
#290 
http://interimm.org/hub/companies/company-o75fxsv1aaeght3ztvo75fxr2e2vwk56/
