### ISSUE TITLE
猴子星球医疗 

### ISSUE THREAD

**Issue by emptymalei** [InterImm/hub#326]
2021-08-30T10:44:17Z

### 作为星际企业数据提交者，我们如何称呼您？

侯星

### ，您的星际企业名称是什么

猴子星球医疗

### 请您选择成立时间

2150-08-30

### 的总部是在哪里

火星视界城(Horizon City)：2148 年成立；子午线城市圈；城内的视界星港是火星最大的星港

### 的企业类型

医疗技术

### 公司详情

猴子星球医疗是专门进行星球间救援以及设备研究的医疗器械与救援机构。

### ，我们如何联系到您？

3055193679@qq.com

**Comment by InterImmCenter** [comment]
#327
