### ISSUE TITLE
火星火辣火锅 

### ISSUE THREAD

**Issue by emptymalei** [InterImm/hub#334]
2021-09-09T10:06:45Z

### 作为星际企业数据提交者，我们如何称呼您？

邹星海

### ，您的星际企业名称是什么

火星火辣火锅

### 请您选择成立时间

2051-09-09

### 的总部是在哪里

火星楼兰城(Kroran City)：2250 年成立；亚马逊城市圈

### 的企业类型

食品

### 公司详情

全太阳系最巴适的火锅店，没有之一！如果你是初临本店的四川或重庆人，可享八折优惠，外送一瓶秘制辣酱。

### ，我们如何联系到您？

1159653074@qq.com

**Comment by InterImmCenter** [comment]
#335 335
