### ISSUE TITLE
柏林先锋那个 tab 好像样式不对

### ISSUE THREAD

**Issue by unionx** [InterImm/hub#35]
http://interimm.org/hub/companies.html 最下面那个，太宽了

**Comment by emptymalei** [comment]
我用的 flex 并不知道如何才能让它固定宽度。因为需要提供一个单独链接，通过css实现的，获取 url 里面的 get parameter 然后突出显示。如果要同时实现这个功能并且要求固定宽度，我想不出应该怎么实现。
