### ISSUE TITLE
μ'sic 

### ISSUE THREAD

**Issue by emptymalei** [InterImm/hub#361]
2021-11-04T14:29:31Z

### 作为星际企业数据提交者，我们如何称呼您？

Ivy_C

### ，您的星际企业名称是什么

μ'sic

### 请您选择成立时间

2061-11-11

### 的总部是在哪里

地球

### 的企业类型

休闲娱乐

### 公司详情

建立于火星殖民早期。其音乐人以曲风多样著称，是音乐界“火星朋克”派的中坚力量。曾为知名音乐游戏_Shyrens_提供大量曲目

### ，我们如何联系到您？

ivyc_here@foxmail.com

**Comment by IvyChere** [comment]
企业类型查半天就是查不到音乐制作
如果可以的话，麻烦帮忙改一下吧XD

**Comment by emptymalei** [comment]
@IvyChere 好的，我现在加上艺术类型。

**Comment by emptymalei** [comment]
#362
