### ISSUE TITLE
维珍银河 - Virgin Galactic 

### ISSUE THREAD

**Issue by emptymalei** [InterImm/hub#420]
2022-02-12T08:17:00Z

### 作为星际企业数据提交者，我们如何称呼您？

暗物质

### ，您的星际企业名称是什么

维珍银河 - Virgin Galactic

### 请您选择成立时间

2022-02-12

### 的总部是在哪里

火星南河城(Procyon City)：2123 年成立；伊希地城市圈

### 的企业类型

太空探索旅游

### 的网址

http://www.Virgin Galactic.com.cn

### 公司详情

：时属维珍集团子公司，其开发的太空船系列亚轨道飞船在 20 世纪 20 年代的亚轨道旅游热潮中占据了大部分市场份额。后并入轨道旅游局。

### ，我们如何联系到您？

darksubstance@126.com

**Comment by IvyChere** [comment]
这位是直接复制粘贴了是吗（地铁老人手机）

----
话说原文的这里

> 其开发的太空船系列亚轨道飞船在 20 世纪 20 年代的亚轨道旅游热潮中占据了大部分市场份额。

时间是不是错了呀，是不是21世纪或者22世纪之类的？

**Comment by emptymalei** [comment]
XD closing because of duplication

#421

**Comment by emptymalei** [comment]
> 这位是直接复制粘贴了是吗（地铁老人手机）
> 
> 话说原文的这里
> 
> > 其开发的太空船系列亚轨道飞船在 20 世纪 20 年代的亚轨道旅游热潮中占据了大部分市场份额。
> 
> 时间是不是错了呀，是不是21世纪或者22世纪之类的？

确实写错了。
