### ISSUE TITLE
Ivy_C 

### ISSUE THREAD

**Issue by emptymalei** [InterImm/hub#513]
2023-08-04T09:52:19Z

### 作为星际企业数据提交者，我们如何称呼您？

快连 - QuiLink

### ，您的星际企业名称是什么

Ivy_C

### 请您选择成立时间

2127-04-06

### 的总部是在哪里

火星南河城(Procyon City)：2123 年成立；伊希地城市圈

### 的企业类型

互联网

### 公司详情

由一些对星际移民局在火星提供的网络质量感到不满的火星技术人员创办，向地外尤其是居民提供稳定、实惠 、高速的网络服务。同时也搭建了一条以安全性闻名的火星-地球虚拟专用网络服务。

“感谢IIA 给火星居民们举办的古早互联网怀旧活动，要不是我的同事提醒我今年是2127年不是1987年，我可能现在还蒙在鼓里。”————来自QuiLink 某匿名创办者。

### ，我们如何联系到您？

ivyc_here@foxmail.coom

**Comment by IvyChere** [comment]
草了
我和它的名字写反了......

**Comment by emptymalei** [comment]
> 草了
> 我和它的名字写反了......

一会儿我在 pull request 里面改过来就可以了

**Comment by IvyChere** [comment]
> 

感谢.....qwq

**Comment by emptymalei** [comment]
#514
