### ISSUE TITLE
Interstellar Transport Company 

### ISSUE THREAD

**Issue by emptymalei** [InterImm/hub#527]
2023-08-19T13:41:36Z

### 作为星际企业数据提交者，我们如何称呼您？

waaaap

### ，您的星际企业名称是什么

Interstellar Transport Company

### 请您选择成立时间

2200-01-01

### 的总部是在哪里

火星南河城(Procyon City)：2123 年成立；伊希地城市圈

### 的企业类型

运输

### 公司详情

Interstellar Transport Company公司，其开发的移民运输业务与为星际移民计划贡献了巨大力量

### ，我们如何联系到您？

1704281159@qq.com

**Comment by emptymalei** [comment]
#528

**Comment by wa-ap** [comment]
> 2023-08-19T13:41:36Z
> 
> ### 作为星际企业数据提交者，我们如何称呼您？
> waaaap
> 
> ### ，您的星际企业名称是什么
> 银环-Interstellar Transport Company
> 
> ### 请您选择成立时间
> 2200-01-01
> 
> ### 的总部是在哪里
> 火星南河城(Procyon City)：2123 年成立；伊希地城市圈
> 
> ### 的企业类型
> 运输
> 
> ### 公司详情
> 银环-Interstellar Transport Company公司，其开发的移民运输业务与为火星星际移民计划贡献了巨大力量
> 
> ### ，我们如何联系到您？
> [1704281159@qq.com](mailto:1704281159@qq.com)



> 2023-08-19T13:41:36Z
> 
> ### 作为星际企业数据提交者，我们如何称呼您？
> waaaap
> 
> ### ，您的星际企业名称是什么
> 银环-Interstellar Transport Company
> 
> ### 请您选择成立时间
> 2200-01-01
> 
> ### 的总部是在哪里
> 火星南河城(Procyon City)：2123 年成立；伊希地城市圈
> 
> ### 的企业类型
> 运输
> 
> ### 公司详情
> 银环-Interstellar Transport Company公司，其开发的移民运输业务与为火星星际移民计划贡献了巨大力量
> 
> ### ，我们如何联系到您？
> [1704281159@qq.com](mailto:1704281159@qq.com)

**Comment by wa-ap** [comment]
帮帮改一下谢谢

**Comment by wa-ap** [comment]
> 帮帮改一下谢谢了(*'▽'*)♪

**Comment by wa-ap** [comment]
> > 2023-08-19T13:41:36Z
> > ### 作为星际企业数据提交者，我们如何称呼您？
> > waaaap
> > ### ，您的星际企业名称是什么
> > 银环-Interstellar Transport Company
> > ### 请您选择成立时间
> > 2200-01-01
> > ### 的总部是在哪里
> > 火星南河城(Procyon City)：2123 年成立；伊希地城市圈
> > ### 的企业类型
> > 运输
> > ### 公司详情
> > 银环-Interstellar Transport Company公司，其开发的移民运输业务与为火星星际移民计划贡献了巨大力量
> > ### ，我们如何联系到您？
> > [1704281159@qq.com](mailto:1704281159@qq.com)
> 
> > 2023-08-19T13:41:36Z
> > ### 作为星际企业数据提交者，我们如何称呼您？
> > waaaap
> > ### ，您的星际企业名称是什么
> > 银环-Interstellar Transport Company
> > ### 请您选择成立时间
> > 2200-01-01
> > ### 的总部是在哪里
> > 火星南河城(Procyon City)：2123 年成立；伊希地城市圈
> > ### 的企业类型
> > 运输
> > ### 公司详情
> > 银环-Interstellar Transport Company公司，2200年1月1日成立，其开发的移民运输业务及空间运输技术的开发为火星家园计划贡献了巨大力量
> > ### ，我们如何联系到您？
> > [1704281159@qq.com](mailto:1704281159@qq.com)

**Comment by wa-ap** [comment]
> > > 2023-08-19T13:41:36Z
> > > ### 作为星际企业数据提交者，我们如何称呼您？
> > > waaaap
> > > ### ，您的星际企业名称是什么
> > > 银环-Interstellar Transport Company
> > > ### 请您选择成立时间
> > > 2200-01-01
> > > ### 的总部是在哪里
> > > 火星南河城(Procyon City)：2123 年成立；伊希地城市圈
> > > ### 的企业类型
> > > 运输
> > > ### 公司详情
> > > 银环-Interstellar Transport Company公司，2200年1月1日成立，其开发的移民运输业务及空间运输技术的开发为火星家园计划贡献了巨大力量
> > > ### ，我们如何联系到您？
> > > [1704281159@qq.com](mailto:1704281159@qq.com)



>

**Comment by emptymalei** [comment]
> > 帮帮改一下谢谢了(_'▽'_)♪

改好了
